<?php

define('PLATFORM_THEME_LAYOUT', 'PLATFORM_THEME_LAYOUT');
define('PLATFORM_URL_ADMIN', 'PLATFORM_URL_ADMIN');
define('PLATFORM_PAGE_TITLE', 'PLATFORM_PAGE_TITLE');
define('PLATFORM_CONFIG_JS', 'PLATFORM_CONFIG_JS');

define('PLATFORM_MIDDLEWARE_API', 'PLATFORM_MIDDLEWARE_API');
define('PLATFORM_MIDDLEWARE_WEB', 'PLATFORM_MIDDLEWARE_WEB');
define('PLATFORM_MIDDLEWARE_ADMIN', 'PLATFORM_MIDDLEWARE_ADMIN');

define('PLATFORM_MIDDLEWARE_BEFORE', 'PLATFORM_MIDDLEWARE_BEFORE');
define('PLATFORM_MIDDLEWARE_AFTER', 'PLATFORM_MIDDLEWARE_AFTER');

define('PLATFORM_ROLE_SUPPER_ADMIN', 'PLATFORM_ROLE_SUPPER_ADMIN');
define('PLATFORM_CHECK_PERMISSION', 'PLATFORM_CHECK_PERMISSION');
define('PLATFORM_CHECK_ROLE', 'PLATFORM_CHECK_ROLE');
define('PLATFORM_PERMISSION_CUSTOME', 'PLATFORM_PERMISSION_CUSTOME');


define('PLATFORM_HEAD_BEFORE', 'PLATFORM_HEAD_BEFORE');
define('PLATFORM_HEAD_AFTER', 'PLATFORM_HEAD_AFTER');
define('PLATFORM_BODY_BEFORE', 'PLATFORM_BODY_BEFORE');
define('PLATFORM_BODY_AFTER', 'PLATFORM_BODY_AFTER');
